name: deploy to heroku

on: 
  push:
    branches: 
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout 
        uses: actions/checkout@v1
        
      - name: setup node
        uses: actions/setup-node@v1
        with: 
          node-version: 12.14.0
      - name: Add remote origin
        run: |
          git remote add heroku https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git
      - name: Deploy to Heroku
        run: |
          git push heroku remotes/origin/develop:master -f
