name: deploy to heroku

on: 
  push:
    branches: 
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout 
        uses: actions/checkout@v1
        
      - name: setup node
        uses: actions/setup-node@v1
        with: 
          node-version: 12.14.0
      - run: git branch -a
      - run: git push https://git.heroku.com/pacific-temple-93679.git remotes/origin/develop:master
      - run: git remote get-url origin
#      - run: npm install

